"""End-to-end pipeline: ingest -> orchestrate -> output guardrails -> citations,
provenance, structured result for the Word/PDF renderer, and an audit log.

Citations are SYSTEM-assigned from the retrieved sources (not authored by the LLM), so
they are consistent and verifiable: each section gets numbered markers [n] and a single
References list maps each number to its source document.
"""
from __future__ import annotations
import os, json, time
from dataclasses import dataclass, field, asdict
from .ingestion import build_stores, ROOT
from .orchestrator import Orchestrator
from .llm_client import MockLLMClient
from . import guardrails as G

REQUIRED = ["Executive Summary","Portfolio Overview","Reserving Position",
            "Solvency (LICAT)","Macroeconomic Sensitivity"]
NUM_RE = G.NUM_RE

# Tables rendered into the report — ALL values pulled from the structured source of truth.
TABLES = [
    ("Portfolio & Pricing", [
        ("Policies in force", "portfolio_policy_count"),
        ("Claim frequency", "portfolio_claim_frequency"),
        ("Mean expected loss / policy", "portfolio_mean_expected_loss_usd"),
        ("Total expected claims", "portfolio_total_expected_claims_usd"),
        ("Gross written premium", "gross_written_premium_usd")]),
    ("Capital & Solvency (LICAT)", [
        ("Policy reserves", "policy_reserves_usd"),
        ("Available capital", "available_capital_usd"),
        ("Required capital", "required_capital_usd"),
        ("LICAT ratio", "licat_ratio_pct"),
        ("Supervisory target", "supervisory_target_pct")]),
    ("Macroeconomic Assumptions", [
        ("Inflation rate", "macro_inflation_rate_pct"),
        ("Discount rate", "discount_rate_pct"),
        ("Wage inflation", "wage_inflation_pct")]),
]

@dataclass
class Audit:
    numeric_ok: bool; unverified_numbers: list; ungrounded_sections: list
    missing_sections: list; input_guardrail_flags: list
    passed: bool = field(init=False)
    def __post_init__(self):
        self.passed = (self.numeric_ok and not self.ungrounded_sections and not self.missing_sections)

@dataclass
class ReportResult:
    report_md: str; audit: Audit; provenance: list; run_log: dict
    sections: list           # [{title, prose, citations:[n]}]
    references: list         # [{n, source, file}]
    tables: list             # [{title, rows:[(label, value_str)]}]
    meta: dict               # period, currency

def _provenance_table(report_md, store):
    prov = store.provenance(); verified = set(prov); rows, seen = [], set()
    for tok in NUM_RE.findall(report_md):
        t = tok.replace("$","").replace(",","").replace("%","")
        try: val = round(float(t),2)
        except ValueError: continue
        if val.is_integer() and abs(val) < 100: continue
        if tok in seen: continue
        seen.add(tok)
        match = next((prov[v] for v in verified if abs(val-v) <= max(0.01, abs(v)*0.005)), None)
        rows.append({"number_in_report": tok, "source": match or "UNVERIFIED", "ok": match is not None})
    return rows

def generate_report(llm=None, embedder_name=None, stores=None):
    t0 = time.time()
    store, vstore, embedder = stores if stores else build_stores(embedder_name)
    from .retriever import Retriever
    llm = llm or MockLLMClient()
    orch = Orchestrator(store, Retriever(vstore), llm)
    raw_sections = orch.build_all()

    # ---- system-assigned citations ----
    order, refs = {}, []
    for s in raw_sections:
        for src in s.sources:
            if src and src not in order:
                order[src] = len(order)+1
                refs.append({"n": order[src], "source": src})
    sections = []
    for s in raw_sections:
        nums = sorted({order[src] for src in s.sources if src in order})
        prose = s.text.split("\n",1)[1].rsplit("\n\n_Sources:",1)[0].strip()  # body only
        marker = "".join(f"[{n}]" for n in nums)
        sections.append({"title": s.title, "prose": f"{prose} {marker}".strip(),
                         "citations": nums, "grounded": s.grounded, "retrieved": s.retrieved})

    # ---- tables from the structured store (all verified numbers) ----
    tables = [{"title": t, "rows": [(label, store.fmt(m)) for label, m in rows]} for t, rows in TABLES]
    meta = {"period": store.get("valuation_period")["value"],
            "currency": store.get("reporting_currency")["value"]}

    # ---- markdown (for reconciliation + audit) ----
    md = [f"# Actuarial Valuation & Solvency Report",
          f"**Period:** {meta['period']}  |  **Currency:** {meta['currency']}",
          "_Draft generated by the GenAI reporting tool. Pending Appointed Actuary sign-off._\n"]
    for s in sections:
        md.append(f"## {s['title']}\n{s['prose']}")
    for t in tables:
        md.append(f"## {t['title']}\n" + "\n".join(f"- {l}: {v}" for l, v in t["rows"]))
    md.append("## References\n" + "\n".join(f"[{r['n']}] {r['source']}" for r in refs))
    md.append("## Actuary's Statement\nReviewed and approved by: ____________________ (Appointed Actuary)")
    report_md = "\n\n".join(md)

    recon = G.reconcile_numbers(report_md, store.verified_numbers())
    ungrounded = [s["title"] for s in sections if not s["grounded"]]
    missing = G.check_template(report_md, REQUIRED)
    input_flags = [f for s in raw_sections for f in s.input_flags]
    audit = Audit(recon.ok, recon.unverified, ungrounded, missing, input_flags)
    prov = _provenance_table(report_md, store)

    run_log = {"timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
               "llm_backend": type(llm).__name__, "embedder": embedder.name,
               "n_corpus_chunks": len(vstore.chunks),
               "sections": [{"title": s["title"], "citations": s["citations"], "grounded": s["grounded"], "retrieved": s["retrieved"]} for s in sections],
               "references": refs, "audit": dict(asdict(audit)),
               "provenance_rows": prov, "duration_sec": round(time.time()-t0,2)}
    logdir = os.path.join(ROOT, "output"); os.makedirs(logdir, exist_ok=True)
    json.dump(run_log, open(os.path.join(logdir,"run_log.json"),"w"), indent=2)
    return ReportResult(report_md, audit, prov, run_log, sections, refs, tables, meta)
